# Generated by Django 3.2 on 2021-04-20 08:08

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.URLField()),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
