# Generated by Django 3.2 on 2021-04-20 09:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_detail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
