# Generated by Django 3.2 on 2021-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_detail_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetImageSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
