# Generated by Django 3.2 on 2021-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_getimagesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getimagesearch',
            name='url',
            field=models.URLField(),
        ),
    ]
