# Generated by Django 3.2 on 2021-04-20 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_getimagesearch_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getimagesearch',
            name='url',
        ),
        migrations.AddField(
            model_name='getimagesearch',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='getimagesearch',
            name='upload',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
