# Generated by Django 3.2 on 2021-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210420_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_image', models.BooleanField(default=False)),
            ],
        ),
    ]
